moviefolder/movieproject/credentials/urls.py
from django.urls import path
from . import views

app_name='credentials'
urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')
]

moviefolder/movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add_movie/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

moviefolder/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

from movieproject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
    path('credentials/',include('credentials.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviefolder/movieproject/credentials/models.py
from django.db import models

# Create your models here.

moviefolder/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='picture')

def __init__(self):
    return self.Movie

moviefolder/movieproject/movieapp/forms.py
from django import forms
from .models import movie



class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

moviefolder/movieproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "invalid credentials")
            return redirect('login')

    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        conpassword = request.POST['password1']
        if password == conpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "usernametaken")
                print("usernametaken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password, first_name=first_name,
                                                last_name=last_name, email=email)

                user.save();
                print("user created")
                return redirect('login')
        else:
            messages.info(request, "password not matched")
            return redirect('register')


    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')

moviefolder/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect

from movieapp.models import movie
from.forms import MovieForm

# Create your views here.
def index(request):
    obj=movie.objects.all()
    return render(request,"index.html",{"result":obj})
def detail(request,movie_id):
    Movie=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{"movie":Movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        Movie=movie(name=name,desc=desc,year=year,img=img)
        Movie.save()

    return render(request,"add.html")
def update(request,id):
    Movie=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{"form":form,"movie":Movie})
def delete(request,id):
    if request.method=='POST':
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

moviefolder/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<br><form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><input type="text" name="name" placeholder="Enter your movie name"></p>
    <p><input type="text" name="desc" placeholder="Enter your movie description"></p>
    <p><input type="text" name="year" placeholder="Enter the movie year"></p>
    <p><input type="file" name="img"></p><br>
    <input type="submit"><br>

</form>

{% endblock %}

moviefolder/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Movie things</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Online Movie store
        <a class="btn btn-success text-left" href="{% url 'movieapp:add_movie' %}">add</a>
        {% if user.is_authenticated %}

        <a class="btn btn-secondary text-right" href="{% url 'credentials:logout'%}">logout</a>
        {% else %}
        <a class="btn btn-primary text-right" href="{% url 'credentials:register' %}">Register</a>
        <a class="btn btn-secondary text-right" href="{% url 'credentials:login' %}">login</a>
        {% endif %}


    </a>
  </div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

moviefolder/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="post" id="fn">
    {% csrf_token %}
    <h4>Are you want to delete this movie?</h4><br>
    <input type="submit" class="btn btn-danger" name="confirm">
</form>


{% endblock %}

moviefolder/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container"><br>
 <div class="row">
  <div class="col-md-6">
   <img src="{{movie.img.url}}" width="250" height="300">

  </div>
<div class="col-md-6">
<h4>{{movie.name}}</h4><br>
 <h6>{{movie.desc}}</h6><br>
 <h4>{{movie.year}}</h4><br>

<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
 </div>
   </div>
</div>
{% endblock %}

moviefolder/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="tn">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Done" class="btn btn-primary">
</form>
    </div>
{% endblock %}

moviefolder/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container"><br>
    <div class="row">
        {% for i in result %}

        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="..." width="250" height="300">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text"></p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View More</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>








{% endblock %}

moviefolder/movieproject/templates/login.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <style>
    body{ text-align:center;
    }
  </style>
</head>
<body>

<form action="login" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Enter your username"><br>
  <input type="password" name="password" placeholder="Enter your password"><br>
  <input type="submit" name="" value="login">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
{% endblock %}
</body>
</html>

moviefolder/movieproject/templates/register.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>

<style>
    body{
    text-align:center
    }
</style>
</head>
<body>
<h2>Register</h2>
<form action="register" method="post">
     {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>
    <input type="text" name="first_name" placeholder="Enter your first_name"><br>
    <input type="text" name="last_name" placeholder="Enter your last_name"><br>
    <input type="email" name="email" placeholder="Enter your email address"><br>
    <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="conpassword" name="password1" placeholder="confirm your password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
{% endblock %}
</body>
</html>